// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB_kaUlI5mLNAKIRjoirytmWx0R9JlH0M',
    appId: '1:484534619681:web:ea6246ae4873ea9396dd60',
    messagingSenderId: '484534619681',
    projectId: 'vrapture',
    authDomain: 'vrapture.firebaseapp.com',
    databaseURL: 'https://vrapture-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vrapture.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZa_3gj7IEjXBNnVRc5gwMfjxojSfQMwE',
    appId: '1:484534619681:android:6c9b179a8af55b6b96dd60',
    messagingSenderId: '484534619681',
    projectId: 'vrapture',
    databaseURL: 'https://vrapture-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vrapture.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdxQOB2t_ZNdFHzHSOk7_kAqL5y-6GKAI',
    appId: '1:484534619681:ios:300c19d2c760fd6296dd60',
    messagingSenderId: '484534619681',
    projectId: 'vrapture',
    databaseURL: 'https://vrapture-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vrapture.appspot.com',
    iosBundleId: 'com.example.vrapture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdxQOB2t_ZNdFHzHSOk7_kAqL5y-6GKAI',
    appId: '1:484534619681:ios:300c19d2c760fd6296dd60',
    messagingSenderId: '484534619681',
    projectId: 'vrapture',
    databaseURL: 'https://vrapture-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vrapture.appspot.com',
    iosBundleId: 'com.example.vrapture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB_kaUlI5mLNAKIRjoirytmWx0R9JlH0M',
    appId: '1:484534619681:web:cfebbc06fa115d8b96dd60',
    messagingSenderId: '484534619681',
    projectId: 'vrapture',
    authDomain: 'vrapture.firebaseapp.com',
    databaseURL: 'https://vrapture-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vrapture.appspot.com',
  );
}
